# Generated by Django 5.2.3 on 2025-07-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_room',
            new_name='chat_room',
        ),
    ]
